### ISSUE TITLE
Win64 build

### ISSUE THREAD

**Issue by vincentxavier** [portapps/nextcloud-portable#1]
Could we have a win64 build of Nextcloud ?

**Comment by crazy-max** [comment]
My bad, Nextcloud Desktop Client 2.5.x is compatible for 64-bits platforms compared to previous versions that are 32-bits compatible
I will push an update for this. Thanks for your input!

**Comment by crazy-max** [comment]
Should be ok : https://portapps.github.io/app/nextcloud-portable/#download
