### ISSUE TITLE
Remove portable quick launch icon in windows explorer

### ISSUE THREAD

**Issue by olsins** [portapps/nextcloud-portable#2]
After I installed the Version I wanted to remove it so I just deleted the Folder (is there an official uninstaller?)
When I installed the program a Nextcloud link was created in the quick launch area of the windows explorer- this one cannot be removed -  Is there a workaround do delete it? S

**Comment by crazy-max** [comment]
Please fill a bug report : https://github.com/portapps/nextcloud-portable/issues/new/choose

**Comment by crazy-max** [comment]
Closed due to inactivity
