### ISSUE TITLE
Nextcloud 3.2 is now available!

### ISSUE THREAD

**Issue by diznanl** [portapps/nextcloud-portable#32]
3.1.3 will not sync when using E2E encryption. Would be great to have the portable version updated to 3.2 so that I can sync on my computer where I have no admin rights :)

https://github.com/nextcloud/desktop/releases/download/v3.2.0/Nextcloud-3.2.0-x64.msi

**Comment by crazy-max** [comment]
Available: https://portapps.io/app/nextcloud-portable/#download
