### ISSUE TITLE
New release with newer upstream version?

### ISSUE THREAD

**Issue by iNtEgraIR2021** [portapps/nextcloud-portable#35]
Hi 👋🏼 

first of all big thank you to everyone involved in this great project for the time and effort needed to keep it running.

Since a few weeks I regularly get notifications by the Nextcloud client reminding me to update.

Would it be possible to release a new version including a newer or if possible the newest upstream version?

As I have no further information about the technical background of this project I can't estimate the time and effort needed to do that. But I'd love to see a new release coming 🥳 

Greetings, Petra 👋🏼

**Comment by crazy-max** [comment]
@iNtEgraIR2021 Available: https://portapps.io/app/nextcloud-portable/#download

**Comment by iNtEgraIR2021** [comment]
Just tested it and it works like a charm! 
Thank you! 👍🏼
