### ISSUE TITLE
Version 3.3.4

### ISSUE THREAD

**Issue by FuzzyMistborn** [portapps/nextcloud-portable#36]
Looks like the latest version is 3.3.4 https://github.com/nextcloud/desktop/releases/tag/v3.3.4.  Portapps release is still 3.2.2.  Any chance of an update?

**Comment by iNtEgraIR2021** [comment]
@crazy-max any chance to update to latest upstream version any time soon?

**Comment by crazy-max** [comment]
https://github.com/portapps/discord-portable/issues/67#issuecomment-859153578

**Comment by FuzzyMistborn** [comment]
In the meantime, I forked and updated myself.  Seems to be working.  https://github.com/FuzzyMistborn/nextcloud-portable/releases/tag/3.3.6-15
