### ISSUE TITLE
Automate Update Process

### ISSUE THREAD

**Issue by GAS85** [portapps/nextcloud-portable#38]
#### Steps to reproduce this issue

1. Open portapps
2. See no new versions since summer 2021
3. See ticket #36 and similar
3. Be sad...

#### Expected behaviour

Automate update/build process and add test steps, so that nobody will open an issue "why newest version is not there".

#### Actual behaviour

Manual update not done, but seems very limited setup is needed...

**Comment by iNtEgraIR2021** [comment]
for now I I'd be very grateful if #37 could be integrated

**Comment by crazy-max** [comment]
https://github.com/portapps/portapps/issues/13
