### ISSUE TITLE
Version 3.5.3 available

### ISSUE THREAD

**Issue by bas89** [portapps/nextcloud-portable#46]
The NextCloud client notifies that a newer version is available. However, in the portable version, it is not possible to automatically (or manually) install the update.

**Comment by anubis-genix** [comment]
3.6.0 is out already

**Comment by Id3aFly** [comment]
Can we somehow support to upgrade to 3.6.1?

**Comment by Id3aFly** [comment]
If time permits I will create an MR for 3.6.4

**Comment by Id3aFly** [comment]
I just created an MR. I'm not sure it will be merged 
https://help.nextcloud.com/t/portable-version-of-windows-desktop-client/12172

However, you can build it yourself: https://portapps.io/doc/contribute/

**Comment by Id3aFly** [comment]
If you are not able to built it yourself, just leave your mail here, I can send the file to you.
