### ISSUE TITLE
Upgrade to version 3.6.6

### ISSUE THREAD

**Issue by ffrediani** [portapps/nextcloud-portable#51]
The current version of Nextcloud portable client is 3.5.1 but the latest released is 3.6.6. Can you upgrade it to the latest version ?
Thanks

**Comment by shadowlmd** [comment]
The project seems abandoned..

**Comment by Id3aFly** [comment]
I'm not sure why this repo is not updated by @crazy-max . He is still active as you can see here: https://portapps.io/news/

However, I just created an MR: https://github.com/portapps/nextcloud-portable/pull/52
You can build it yourself: https://portapps.io/doc/contribute/

**Comment by Id3aFly** [comment]
If you are not able to built it yourself, just leave your mail here, I can send the file to you.
