### ISSUE TITLE
Variable config location

### ISSUE THREAD

**Issue by Aesculapius** [portapps/nextcloud-portable#7]
Used to use an older portable version of the owncloud client and wanted to make the jump to Nextcloud client.

At work, I can let the files be placed on a share where they are whitelisted from executable rights. But that's a general place so no good place to store configuration (and there are no write rights afterwards). So I need to store the configuration containing accounts etc. on a home-folder.

In de older owncloud portable, there was a .ini file in the root containing the lines:

>[GENERAL]
>application = App\owncloud.exe
>commandline = --confdir T:\ocConfig

where T is the personal home share with write access (but no executable access).

Is such a thing possible with this client? It looks like it has some config possibilities with yaml/json, but I can't find out where or how to set up....

**Comment by crazy-max** [comment]
@Aesculapius,

After study, this improvement is not possible because it defeats the portable purpose.

Unlike portapps/portapps#28, this could also cause unexpected behaviour because the wrapper is strongly linked to its configuration file (and logs) and so cannot be shared.
