### ISSUE TITLE
why a virus?

### ISSUE THREAD

**Issue by daledali** [portapps/nextcloud-portable#8]
Antiy-AVL GrayWare/Win32.Kryptik.BQX
CrowdStrike Falcon Win/malicious_confidence_60% (W)

![image](https://user-images.githubusercontent.com/51318912/74296293-3a2f4c00-4cf8-11ea-9243-b3425720eac8.png)

**Comment by crazy-max** [comment]
https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper
